Repository 21cmfast/21cmFAST, pull requests merged in 2020-10, with the labels that each got.

#174 Address Sultan's Comments on Paper
  INSTALLATION.rst
  README.rst
  docs/tutorials/coeval_cubes.ipynb
  src/py21cmfast/_utils.py
  src/py21cmfast/cli.py
  src/py21cmfast/outputs.py
  src/py21cmfast/plotting.py
  user_data/runconfig_example.yml
Labels: context: python wrapper, type: documentation, type: feature: code

#188 Add Acknowledgment Refs
  README.rst
Labels: type: documentation

#181 fix some major memory leak (+ some small leak...)
  src/py21cmfast/src/21cmFAST.h
  src/py21cmfast/src/GenerateICs.c
  src/py21cmfast/src/IonisationBox.c
  src/py21cmfast/src/SpinTemperatureBox.c
  src/py21cmfast/src/heating_helper_progs.c
  src/py21cmfast/src/ps.c
  src/py21cmfast/wrapper.py
Labels: context: C backend, status: requires discussion, type: maintenance, type: performance: memory
